apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret-<name>
    shareName: <file-share-name>
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=10000
    - gid=10000
    - mfsymlinks
    - nobrl
