kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: pv-azurefile
